### ISSUE TITLE
Bilder und Grafiken in Anhang verschieben

### ISSUE THREAD

**Issue by captainwuushuu** [StefanieJaeger/sa-docu#10]
Bilder und Grafiken gehören hauptsächlich in den Anhang, dann darauf verweisen an entsprechenden Stellen im Hauptteil.

**Comment by StefanieJaeger** [comment]
Mer isch no ufgfalle, dass mer ide Caption de Text amigs in Aführigszeiche hend und amigs nit. Öffters mit als ohni, wemer uf immer mit umstelle?

**Comment by StefanieJaeger** [comment]
Ibundeni Files hend zT selber es Kapitel uf Heading Level 1, mer sette die automatisch unter schiebe.
